import React from 'react';
import Header from '../components/Header';
import LeftSidebar from '../components/LeftSidebar';
import RightSidebar from '../components/RightSidebar';
import Footer from '../components/Footer';
// Fix: Removed unused and non-existent icon imports (BulbIcon, NewsIcon, EfficiencyIcon, GridIcon) and added LearnIcon as a replacement for NewsIcon.
import { SolarIcon, WindIcon, LngIcon, PngIcon, CbgIcon, AwarenessIcon, LearnIcon } from '../components/Icons';

const awarenessTopics = [
  {
    icon: <SolarIcon />,
    title: 'The Power of Solar Energy',
    description: 'Solar power is a leading renewable energy source. It converts sunlight into electricity using photovoltaic (PV) panels, significantly reducing greenhouse gas emissions and reliance on fossil fuels. It\'s a key solution for a sustainable future.',
    category: 'Renewable Energy'
  },
  {
    icon: <WindIcon />,
    title: 'Harnessing the Wind',
    description: 'Wind turbines capture kinetic energy from the wind and convert it into electricity. Onshore and offshore wind farms are becoming increasingly common, providing clean energy to power homes and industries with minimal environmental impact.',
    category: 'Renewable Energy'
  },
  {
    icon: <LngIcon />,
    title: 'LNG: A Cleaner Fossil Fuel',
    description: 'Liquefied Natural Gas (LNG) is natural gas that has been cooled to a liquid state for easier transport and storage. While a fossil fuel, it burns much cleaner than coal or oil, producing fewer emissions, making it a transitional fuel towards a greener future.',
    category: 'Transitional Fuels'
  },
  {
    icon: <PngIcon />,
    title: 'PNG for Domestic Use',
    description: 'Piped Natural Gas (PNG) is a safe and reliable energy source delivered directly to homes and businesses. It\'s primarily used for cooking and heating, offering a more efficient and less polluting alternative to traditional LPG cylinders.',
    category: 'Domestic Energy'
  },
  {
    icon: <CbgIcon />,
    title: 'CBG: Energy from Waste',
    description: 'Compressed Bio-Gas (CBG) is a renewable fuel produced from organic waste materials like agricultural residue, cattle dung, and municipal solid waste. It promotes a circular economy by turning waste into a valuable energy resource.',
    category: 'Bio-Energy'
  },
   {
    // Fix: Replaced non-existent NewsIcon with the existing and suitable LearnIcon.
    icon: <LearnIcon />,
    title: 'Understanding Your Carbon Footprint',
    description: 'Your carbon footprint is the total amount of greenhouse gases generated by your actions. By understanding it, you can make informed choices to reduce your impact, such as using public transport, conserving electricity, and adopting a sustainable diet.',
    category: 'Environmental Impact'
  }
];

const mythAndFactTopics = [
    {
        myth: "Renewable energy is too expensive for the average consumer.",
        fact: "The cost of solar panels and wind turbines has dropped by over 80% in the last decade, making them competitive with fossil fuels in many regions."
    },
    {
        myth: "Clean energy is unreliable; it only works when the sun is shining or the wind is blowing.",
        fact: "Modern energy grids use a mix of sources and advanced battery storage systems to ensure a consistent and reliable power supply, even when renewables are not generating."
    },
    {
        myth: "Switching to cleaner energy sources won't make a big difference.",
        fact: "Transitioning to renewables is the single most effective way to combat climate change. Widespread adoption could cut global greenhouse gas emissions by up to 70%."
    },
    {
        myth: "Solar panels require a lot of maintenance.",
        fact: "Solar panels are incredibly durable and require very little maintenance, typically just periodic cleaning. Most come with a 20-25 year warranty."
    },
    {
        myth: "Wind turbines are noisy and harmful to wildlife.",
        fact: "Technological advancements have made modern turbines much quieter. With proper placement and planning, risks to wildlife can be significantly minimized."
    }
];

const AwarenessCard: React.FC<typeof awarenessTopics[0]> = ({ icon, title, description, category }) => (
    <div className="bg-[#2a211c]/80 border border-amber-900/50 rounded-2xl p-6 backdrop-blur-sm flex flex-col h-full">
        {icon && <div className="w-10 h-10 mb-4 text-amber-400">{icon}</div>}
        <p className="font-poppins text-xs font-bold tracking-widest text-amber-400 uppercase mb-2">{category}</p>
        <h3 className="font-poppins text-xl font-bold text-white tracking-wider mb-3">{title}</h3>
        <p className="text-white/70 text-sm leading-relaxed">{description}</p>
    </div>
);

const MythFactCard: React.FC<typeof mythAndFactTopics[0]> = ({ myth, fact }) => (
    <div className="bg-[#2a211c]/80 border border-amber-900/50 rounded-2xl p-6 backdrop-blur-sm flex flex-col h-full">
        <div className="mb-4">
            <p className="font-poppins text-xs font-bold tracking-widest text-red-400 uppercase mb-2">Myth</p>
            <p className="text-white/80 text-sm italic">"{myth}"</p>
        </div>
        <div className="mt-auto pt-4 border-t border-amber-800/40">
            <p className="font-poppins text-xs font-bold tracking-widest text-green-400 uppercase mb-2">Fact</p>
            <p className="text-white/90 text-sm font-semibold">{fact}</p>
        </div>
    </div>
);


const AwarenessPage: React.FC = () => {
    return (
        <div className="w-full min-h-screen text-white bg-black">
            <video autoPlay loop muted playsInline className="fixed top-0 left-0 w-full h-full object-cover z-0">
                <source src="https://res.cloudinary.com/do2bp6ryt/video/upload/v1761332572/Video_Generation_with_Rightward_Movement_1_y81nr0.mp4" type="video/mp4" />
            </video>
            <div className="fixed top-0 left-0 w-full h-full bg-black/50 z-10"></div>
            <div className="relative z-20">
                <Header />
                <LeftSidebar />
                <RightSidebar />
                <main className="min-h-screen flex flex-col items-center justify-center pt-32 pb-16">
                    <div className="text-center mb-12 px-4">
                        <h1 className="font-poppins text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-wide drop-shadow-[0_0_8px_rgba(251,191,36,0.8)] flex items-center justify-center">
                            <AwarenessIcon />
                            <span className="ml-4">Clean Energy Awareness</span>
                        </h1>
                        <p className="mt-4 text-white/70 text-lg max-w-3xl mx-auto">Learn about different energy sources and how they impact our world. Knowledge is the first step towards a sustainable future.</p>
                    </div>

                    <div className="w-full relative overflow-hidden group py-6">
                        <div className="flex w-max animate-marquee group-hover:[animation-play-state:paused]">
                            {[...awarenessTopics, ...awarenessTopics].map((topic, index) => (
                                <div key={index} className="w-[350px] shrink-0 mx-3">
                                    <AwarenessCard {...topic} />
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="w-full relative overflow-hidden group py-6">
                        <div className="flex w-max animate-marquee-reverse group-hover:[animation-play-state:paused]">
                            {[...mythAndFactTopics, ...mythAndFactTopics].map((topic, index) => (
                                <div key={index} className="w-[350px] shrink-0 mx-3">
                                    <MythFactCard {...topic} />
                                </div>
                            ))}
                        </div>
                    </div>
                </main>
                <Footer />
            </div>
             <style>{`
                @keyframes marquee {
                    0% { transform: translateX(0%); }
                    100% { transform: translateX(-50%); }
                }
                .animate-marquee {
                    animation: marquee 80s linear infinite;
                }
                @keyframes marquee-reverse {
                    0% { transform: translateX(-50%); }
                    100% { transform: translateX(0%); }
                }
                .animate-marquee-reverse {
                    animation: marquee-reverse 80s linear infinite;
                }
            `}</style>
        </div>
    );
};

export default AwarenessPage;